### ISSUE TITLE
Rails 3 Development mode crashes after the first usage of ImageMagick

### ISSUE THREAD

**Issue by bf4** [gemhome/rmagick#13]
<a href="https://github.com/jeffdeville"><img src="https://avatars.githubusercontent.com/u/131664?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jeffdeville](https://github.com/jeffdeville)**
_Saturday Jan 08, 2011 at 06:10 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/22_

----

The error message is:
cannot remove Object::Version

I think what's happening is that in development mode, Rails tries to clear itself, and reload the environment somewhat after each page. It's this process that is dying.  (The code that actually manipulates my image works, and setting cache_classes: true avoids the problem, but makes it necessary to restart my development server constantly.

Stacktrace:

```
activesupport (3.0.3) lib/active_support/dependencies.rb:645:in `remove_const'
activesupport (3.0.3) lib/active_support/dependencies.rb:645:in `remove_constant'
activesupport (3.0.3) lib/active_support/dependencies.rb:645:in `instance_eval'
activesupport (3.0.3) lib/active_support/dependencies.rb:645:in `remove_constant'
activesupport (3.0.3) lib/active_support/dependencies.rb:521:in `remove_unloadable_constants!'
activesupport (3.0.3) lib/active_support/dependencies.rb:521:in `each'
activesupport (3.0.3) lib/active_support/dependencies.rb:521:in `remove_unloadable_constants!'
activesupport (3.0.3) lib/active_support/dependencies.rb:317:in `clear'
railties (3.0.3) lib/rails/application/bootstrap.rb:60:in `_callback_after_7'
activesupport (3.0.3) lib/active_support/callbacks.rb:419:in `_run_call_callbacks'
actionpack (3.0.3) lib/action_dispatch/middleware/callbacks.rb:44:in `call'
rack (1.2.1) lib/rack/sendfile.rb:107:in `call'
actionpack (3.0.3) lib/action_dispatch/middleware/remote_ip.rb:48:in `call'
actionpack (3.0.3) lib/action_dispatch/middleware/show_exceptions.rb:46:in `call'
railties (3.0.3) lib/rails/rack/logger.rb:13:in `call'
rack (1.2.1) lib/rack/runtime.rb:17:in `call'
activesupport (3.0.3) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.2.1) lib/rack/lock.rb:11:in `call'
rack (1.2.1) lib/rack/lock.rb:11:in `synchronize'
rack (1.2.1) lib/rack/lock.rb:11:in `call'
actionpack (3.0.3) lib/action_dispatch/middleware/static.rb:30:in `call'
railties (3.0.3) lib/rails/application.rb:168:in `call'
railties (3.0.3) lib/rails/application.rb:77:in `send'
railties (3.0.3) lib/rails/application.rb:77:in `method_missing'
railties (3.0.3) lib/rails/rack/log_tailer.rb:14:in `call'
rack (1.2.1) lib/rack/content_length.rb:13:in `call'
rack (1.2.1) lib/rack/handler/webrick.rb:52:in `service'
/Volumes/files/jeffdeville/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
/Volumes/files/jeffdeville/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
/Volumes/files/jeffdeville/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
/Volumes/files/jeffdeville/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/1.8/webrick/server.rb:162:in `start'
/Volumes/files/jeffdeville/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
/Volumes/files/jeffdeville/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/1.8/webrick/server.rb:95:in `start'
/Volumes/files/jeffdeville/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/1.8/webrick/server.rb:92:in `each'
/Volumes/files/jeffdeville/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/1.8/webrick/server.rb:92:in `start'
/Volumes/files/jeffdeville/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/1.8/webrick/server.rb:23:in `start'
/Volumes/files/jeffdeville/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/1.8/webrick/server.rb:82:in `start'
rack (1.2.1) lib/rack/handler/webrick.rb:13:in `run'
rack (1.2.1) lib/rack/server.rb:213:in `start'
railties (3.0.3) lib/rails/commands/server.rb:65:in `start'
railties (3.0.3) lib/rails/commands.rb:30
railties (3.0.3) lib/rails/commands.rb:27:in `tap'
railties (3.0.3) lib/rails/commands.rb:27
script/rails:6:in `require'
script/rails:6
```

**Comment by vassilevsky** [comment]
@jeffdeville @wfwalker hello :) Is this problem still around? Rails has seen many new versions and RMagick has been updated too.

**Comment by wfwalker** [comment]
Hi @vassilevsky thanks for asking, I'm not seeing this problem any more. I'm happy to see this get closed and then file a new issue if it comes back.

**Comment by jeffdeville** [comment]
Yeah, just close it at this point. I'm sure someone will let you know if it's still an issue.

**Comment by vassilevsky** [comment]
👍
